services:
  - type: web
    name: webzee-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
